### PR TITLE
chore: Updated CHANGELOG for v1.0.0 release

### PR DESCRIPTION
**Pull request by stevehipwell**
@patrick-stephens we can add a bit more to the CHANGELOG if you like? Once this is merged the `v1.0.0` tag needs to be added to create the release.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
I'll let you push the tag mate.

**Review by patrick-stephens — APPROVED** [review]

**Comment by stevehipwell** [comment]
@patrick-stephens could you check that `v*` tags are protected?

**Comment by patrick-stephens** [comment]
They are not so let me add.

**Comment by patrick-stephens** [comment]
They are now.

**Pull request merged**
